name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install XDO Dependency
      run: sudo apt-get install libxdo-dev mingw-w64
    - name: Install windows rustc target
      run: rustup target add x86_64-pc-windows-gnu
    - name: Build Linux
      run: cargo build --release
    - name: Build Windows
      run: cargo build --target x86_64-pc-windows-gnu --release
    - uses: actions/upload-artifact@v3
      with:
        path: |
          target/release/am
          target/x86_64-pc-windows-gnu/release/am.exe


