name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install XDO Dependency
      run: sudo apt-get install libxdo-dev
    #- name: Build
    #  run: cargo build --verbose
    - name: Build sources
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release

